name: PR Commenter
on:
  pull_request:
    branches:
      - main

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Package
        run: pip install openai ./ai_code_review

      - name: Write API Key to File
        run: echo "${{ secrets.API_KEY }}" > api_key.txt

      - name: Get list of files
        id: files
        uses: actions/github-script@v6
        with:
          script: |
            const pull_number = context.issue.number;
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number
            });
            return files.map(f => f.filename);

      - name: Run Script on Each File and Save Outputs
        id: output
        run: |
          files=$(echo '${{ steps.files.outputs.result }}' | jq -r '.[]')
          echo "these are the files"
          echo $files
          outputs=""
          for file in $files; do
            output="test run ok"
            outputs="${outputs}{\"path\":\"${file}\",\"review\":\"${output}\"},"
          done
          outputs="[$(echo -n $outputs | head -c -1)]"
          echo "${outputs}"
          echo "::set-output name=result::$outputs"
        env:
          PYTHONIOENCODING: utf-8
          
      - name: Comment On Each File
        id: comments
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            echo "echoing";
            

