name: PR Commenter
on:
  pull_request:
    branches:
      - main

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Package
        run: pip install openai ./ai_code_review

      - name: Write API Key to File
        run: echo "${{ secrets.API_KEY }}" > api_key.txt

      - name: Get list of files
        id: files
        uses: actions/github-script@v5
        with:
          script: |
            const pull_number = context.issue.number;
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number
            });
            return files.map(f => f.filename);

      - name: Run Script on Each File and Save Outputs
        id: outputs
        run: |
          files=$(echo '${{ steps.files.outputs.result }}' | jq -r '.[]')
          outputs=""
          for file in $files; do
            output=$(gpt_review -a ./api_key.txt -f $file)
            outputs="${outputs}{\"file\":\"${file}\",\"output\":\"${output}\"},"
          done
          outputs="[$(echo -n $outputs | head -c -1)]"
          echo "::set-output name=result::$outputs"
        env:
          PYTHONIOENCODING: utf-8

      - name: Comment on Each File
        uses: actions/github-script@v5
        with:
          script: |
            const issue_number = context.issue.number;
            const outputs = ${{ fromJson(steps.outputs.result) }};
            for (let i = 0; i < outputs.length; i++) {
              const fileOutput = outputs[i];
              const file = fileOutput.file;
              const output = fileOutput.output;
              await github.pulls.createReviewComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: issue_number,
                commit_id: context.sha,
                path: file,
                position: 1, // Update this to the actual line number where you want to post the comment
                body: output
              });
            }
